cas: {baseLmallDomain: 'http://offlinelmall.lianjia.com:8971', clientCasUrl: 'http://offlinelmall.lianjia.com:8971/cas',
  filterLoginUrl: 'http://passport.off.lianjia.com/cas/login?service=http://offlinelmall.lianjia.com:8971/cas',
  indexUrl: 'http://offlinelmall.lianjia.com:8971/static/', logoutUrl: 'http://passport.off.lianjia.com/cas/logout',
  serverCasUrl: 'http://passport.off.lianjia.com/cas'}
db: {host: 172.30.11.202, name: commerce_platform, port: 3312, pwd: homelink, user: root}
redis: {databaseNum: 2, host: 172.30.11.218, port: 6307}
server: {port: 8071}
user: {baseUrl: 'http://172.30.19.217:5100/'}

pay: {
    lcoinWithholdPayUrl: 'http://offlinepay.lmall.lianjia.com:8060/api/payment/lcoin/withhold',
    withholdRefundUrl: 'http://offlinepay.lmall.lianjia.com:8060/api/refund',
    cashierPayUrl: 'http://offlinepay.lmall.lianjia.com:8060/cashier/pay',
    redirectUrl: 'http://offlinelmall.lianjia.com:8971/static/index.html#order',
    callbackUrl: 'http://offlinelmall.lianjia.com:8971/api/order/pay/callback'}