server:
  port: 8888

db:
  host: 10.10.6.52
  port: 6523
  name: commerce_platform
  user: web_w
  pwd: 55b114626bcf33bab048a15049b4bbbf

redis:
  host: 10.10.8.35
  port: 6379
  databaseNum: 2

cas:
  baseLmallDomain: http://lmall.lianjia.com
  serverCasUrl: http://passport.lianjia.com/cas
  clientCasUrl: http://lmall.lianjia.com/cas
  filterLoginUrl: http://passport.lianjia.com/cas/login?service=http://lmall.lianjia.com/cas
  logoutUrl: http://passport.lianjia.com/cas/logout
  indexUrl: http://lmall.lianjia.com/

user:
    baseUrl: http://uc.lianjia.com

pay:
  lcoinWithholdPayUrl: http://pay.lmall.lianjia.com/api/payment/lcoin/withhold
  withholdRefundUrl: http://pay.lmall.lianjia.com/api/refund
  cashierPayUrl: http://pay.lmall.lianjia.com/cashier/pay
  redirectUrl: http://pay.lmall.lianjia.com/static/index.html#order
  callbackUrl: http://pay.lmall.lianjia.com/api/order/pay/callback